# ./ansible-tomcat/tasks/install_cje.yml

- name: nfs-utils | Installing nfs-utils
  yum:
    name: nfs-utils
    state: latest

- name: tomcat | Downloading tomcat 8
  get_url: url=http://mirror.nexcess.net/apache/tomcat/tomcat-8/v8.0.33/bin/apache-tomcat-8.0.33.tar.gz dest=/home/ec2-user/ mode=0644

- name: tomcat | Untaring tomcat
  command: 'sudo tar xvf apache-tomcat-8.0.33.tar.gz'
  args:
    chdir: /home/ec2-user
    creates: "/home/ec2-user/apache-tomcat-8.0.33" 

- name: tomcat | removing tomcat webapps 
  command: 'sudo rm -rf *'
  args:
    chdir: /home/ec2-user/apache-tomcat-8.0.33/webapps/

- name: jenkins | Downloading jenkins
  get_url: url=http://nectar-downloads.cloudbees.com/cje/1.642/war/1.642.4.1/jenkins.war dest=/home/ec2-user/apache-tomcat-8.0.33/webapps mode=0644

- name: jenkins | move war  
  command: 'sudo mv jenkins.war ROOT.war'
  args:
    chdir: /home/ec2-user/apache-tomcat-8.0.33/webapps/
    creates: "/home/ec2-user/apache-tomcat-8.0.33/webapps/ROOT.xml"

- template: src=templates/setup.sh dest=/home/ec2-user/setup.sh owner=ec2-user group=ec2-user mode=0755
