# ./ansible-tomcat/tasks/install_cje.yml

- name: tomcat | Downloading tomcat 8
  get_url: url=http://mirror.nexcess.net/apache/tomcat/tomcat-8/v8.0.33/bin/apache-tomcat-8.0.33.tar.gz dest=/home/ec2-user/ mode=0644 timeout=20

- name: tomcat | Untaring tomcat
  command: 'sudo tar xvf apache-tomcat-8.0.33.tar.gz'
  args:
    chdir: /home/ec2-user
    creates: "/home/ec2-user/apache-tomcat-8.0.33" 

- name: tomcat | removing tomcat webapps 
  command: 'sudo /usr/bin/rm -rf *'
  args:
    chdir: /home/ec2-user/apache-tomcat-8.0.33/webapps/

- name: cjoc | Downloading cjoc
  get_url: url=http://downloads.cloudbees.com/cjoc/1.625/war/1.625.16.2/jenkins-oc.war dest=/home/ec2-user/apache-tomcat-8.0.33/webapps mode=0644

- name: jenkins | move war  
  command: 'sudo mv jenkins-oc.war ROOT.war'
  args:
    chdir: /home/ec2-user/apache-tomcat-8.0.33/webapps/

- name: tomcat | removing tomcat webapps 
  command: 'shopt -s extglob; sudo /usr/bin/rm -rf !(ROOT.war)'
  args:
    chdir: /home/ec2-user/apache-tomcat-8.0.33/webapps/

