# ./ansible-nginx/tasks/install_nginx.yml
 
- name: NGINX | Installing NGINX repo rpm
  yum:
    name: http://nginx.org/packages/rhel/7/x86_64/RPMS/nginx-1.8.1-1.el7.ngx.x86_64.rpm 
 
- name: NGINX | Installing NGINX
  yum:
    name: nginx
    state: latest

- template: src=templates/tomcat.conf.j2 dest=/etc/nginx/conf.d/tomcat.conf owner=root group=root mode=0644
 
- name: NGINX | Starting NGINX
  service:
    name: nginx
    state: started

- name: NGINX | semanage port 7070 
  command: "sudo semanage port -a -t http_port_t  -p tcp 7070"
  args:
    chdir: /home/ec2-user

- name: NGINX | audit2allow nginx 
  command: "sudo cat /var/log/audit/audit.log | grep nginx | grep denied | audit2allow -M mynginx"
  args:
    chdir: /home/ec2-user

- name: NGINX | audit2allow nginx 
  command: "sudo semodule -i mynginx.pp"
  args:
    chdir: /home/ec2-user

