# ./ansible-cjoc/deploy.yml

- hosts: cjoc_hosts
  sudo: true
  vars:
    tomcat_url: http://mirror.nexcess.net/apache/tomcat/tomcat-8/v8.0.33/bin/apache-tomcat-8.0.33.tar.gz
    tomcat_tarball: apache-tomcat-8.0.33.tar.gz
    tomcat_untared: apache-tomcat-8.0.33
    cjoc_url: http://downloads.cloudbees.com/cjoc/1.625/war/1.625.16.2/jenkins-oc.war
  tasks:
    - include: 'tasks/install_cjoc.yml'
