# ./ansible-java/tasks/install_java.yml

- name: wget | Installing wget 
  yum:
    name: wget
    state: latest
 
- name: JAVA | Downloading Java
  command: 'sudo wget --no-cookies --no-check-certificate --header "Cookie: gpw_e24=http%3A%2F%2Fwww.oracle.com%2F; oraclelicense=accept-securebackup-cookie" "http://download.oracle.com/otn-pub/java/jdk/8u45-b14/server-jre-8u45-linux-x64.tar.gz"' 
  args:
    chdir: /opt
    creates: "server-jre-8u45-linux-x64.tar.gz" 

- name: JAVA | Untaring Java
  command: 'sudo tar xvf server-jre-8u45-linux-x64.tar.gz'
  args:
    chdir: /opt
    creates: "/opt/jdk1.8.0_45" 

- name: JAVA | chown Java
  command: 'sudo chown -R root: jdk1.8.0_45'
  args:
    chdir: /opt

- name: JAVA | alternatives Java
  command: 'sudo alternatives --install /usr/bin/java java /opt/jdk1.8.0_45/bin/java 1'
  args:
    chdir: /opt

- name: JAVA | alternatives jar 
  command: 'sudo alternatives --install /usr/bin/jar jar /opt/jdk1.8.0_45/bin/jar 1'
  args:
    chdir: /opt

